# Generated by Django 6.0.2 on 2026-02-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='curation',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='last_field',
            new_name='last_name',
        ),
    ]
