# Generated by Django 6.0.2 on 2026-02-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_rename_curation_course_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_field',
            new_name='last_name',
        ),
    ]
